// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.30.2
// source: contract/protobuf/matching/matching.proto

package matching

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchedUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	UserIds       []uint64               `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchedUsers) Reset() {
	*x = MatchedUsers{}
	mi := &file_contract_protobuf_matching_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedUsers) ProtoMessage() {}

func (x *MatchedUsers) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_matching_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedUsers.ProtoReflect.Descriptor instead.
func (*MatchedUsers) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_matching_matching_proto_rawDescGZIP(), []int{0}
}

func (x *MatchedUsers) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MatchedUsers) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_contract_protobuf_matching_matching_proto protoreflect.FileDescriptor

const file_contract_protobuf_matching_matching_proto_rawDesc = "" +
	"\n" +
	")contract/protobuf/matching/matching.proto\x12\bmatching\"E\n" +
	"\fMatchedUsers\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x04R\auserIdsB\x1fZ\x1dcontract/protogolang/matchingb\x06proto3"

var (
	file_contract_protobuf_matching_matching_proto_rawDescOnce sync.Once
	file_contract_protobuf_matching_matching_proto_rawDescData []byte
)

func file_contract_protobuf_matching_matching_proto_rawDescGZIP() []byte {
	file_contract_protobuf_matching_matching_proto_rawDescOnce.Do(func() {
		file_contract_protobuf_matching_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_protobuf_matching_matching_proto_rawDesc), len(file_contract_protobuf_matching_matching_proto_rawDesc)))
	})
	return file_contract_protobuf_matching_matching_proto_rawDescData
}

var file_contract_protobuf_matching_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contract_protobuf_matching_matching_proto_goTypes = []any{
	(*MatchedUsers)(nil), // 0: matching.MatchedUsers
}
var file_contract_protobuf_matching_matching_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_protobuf_matching_matching_proto_init() }
func file_contract_protobuf_matching_matching_proto_init() {
	if File_contract_protobuf_matching_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_protobuf_matching_matching_proto_rawDesc), len(file_contract_protobuf_matching_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_protobuf_matching_matching_proto_goTypes,
		DependencyIndexes: file_contract_protobuf_matching_matching_proto_depIdxs,
		MessageInfos:      file_contract_protobuf_matching_matching_proto_msgTypes,
	}.Build()
	File_contract_protobuf_matching_matching_proto = out.File
	file_contract_protobuf_matching_matching_proto_goTypes = nil
	file_contract_protobuf_matching_matching_proto_depIdxs = nil
}
