// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.30.2
// source: contract/protobuf/presence/presence.proto

package presence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_contract_protobuf_presence_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_presence_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_presence_presence_proto_rawDescGZIP(), []int{0}
}

func (x *GetPresenceRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetPresenceItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_contract_protobuf_presence_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_presence_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_presence_presence_proto_rawDescGZIP(), []int{1}
}

func (x *GetPresenceResponse) GetItems() []*GetPresenceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetPresenceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceItem) Reset() {
	*x = GetPresenceItem{}
	mi := &file_contract_protobuf_presence_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceItem) ProtoMessage() {}

func (x *GetPresenceItem) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protobuf_presence_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceItem.ProtoReflect.Descriptor instead.
func (*GetPresenceItem) Descriptor() ([]byte, []int) {
	return file_contract_protobuf_presence_presence_proto_rawDescGZIP(), []int{2}
}

func (x *GetPresenceItem) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPresenceItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_contract_protobuf_presence_presence_proto protoreflect.FileDescriptor

const file_contract_protobuf_presence_presence_proto_rawDesc = "" +
	"\n" +
	")contract/protobuf/presence/presence.proto\x12\bpresence\"/\n" +
	"\x12GetPresenceRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"F\n" +
	"\x13GetPresenceResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.presence.GetPresenceItemR\x05items\"H\n" +
	"\x0fGetPresenceItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2]\n" +
	"\x0fPresenceService\x12J\n" +
	"\vGetPresence\x12\x1c.presence.GetPresenceRequest\x1a\x1d.presence.GetPresenceResponseB\x1fZ\x1dcontract/protogolang/presenceb\x06proto3"

var (
	file_contract_protobuf_presence_presence_proto_rawDescOnce sync.Once
	file_contract_protobuf_presence_presence_proto_rawDescData []byte
)

func file_contract_protobuf_presence_presence_proto_rawDescGZIP() []byte {
	file_contract_protobuf_presence_presence_proto_rawDescOnce.Do(func() {
		file_contract_protobuf_presence_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_protobuf_presence_presence_proto_rawDesc), len(file_contract_protobuf_presence_presence_proto_rawDesc)))
	})
	return file_contract_protobuf_presence_presence_proto_rawDescData
}

var file_contract_protobuf_presence_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contract_protobuf_presence_presence_proto_goTypes = []any{
	(*GetPresenceRequest)(nil),  // 0: presence.GetPresenceRequest
	(*GetPresenceResponse)(nil), // 1: presence.GetPresenceResponse
	(*GetPresenceItem)(nil),     // 2: presence.GetPresenceItem
}
var file_contract_protobuf_presence_presence_proto_depIdxs = []int32{
	2, // 0: presence.GetPresenceResponse.items:type_name -> presence.GetPresenceItem
	0, // 1: presence.PresenceService.GetPresence:input_type -> presence.GetPresenceRequest
	1, // 2: presence.PresenceService.GetPresence:output_type -> presence.GetPresenceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contract_protobuf_presence_presence_proto_init() }
func file_contract_protobuf_presence_presence_proto_init() {
	if File_contract_protobuf_presence_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_protobuf_presence_presence_proto_rawDesc), len(file_contract_protobuf_presence_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_protobuf_presence_presence_proto_goTypes,
		DependencyIndexes: file_contract_protobuf_presence_presence_proto_depIdxs,
		MessageInfos:      file_contract_protobuf_presence_presence_proto_msgTypes,
	}.Build()
	File_contract_protobuf_presence_presence_proto = out.File
	file_contract_protobuf_presence_presence_proto_goTypes = nil
	file_contract_protobuf_presence_presence_proto_depIdxs = nil
}
